name: Rust

on:
  push:
    branches: [ "main", "ci-patch-1" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  deployments: write

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run benchmark
      working-directory: ./rust
      run: cargo bench -- --output-format bencher | tee output.txt
    - name: Store benchmark result  
      uses: benchmark-action/github-action-benchmark@v1
      with:
          tool: 'cargo'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file-path: rust/output.txt
          gh-pages-branch: 
          # gh-repository: 'github.com/benchmark-action/github-action-benchmark-results'
          auto-push: true
    # - name: Trigger next workflow
    #   if: success()
    #   uses: peter-evans/repository-dispatch@v1
    #   with:
    #     token: ${{ secrets.REPO_GHA_PAT }}
    #     repository: ${{ github.repository }}
    #     event-type: trigger-workflow-2
    #     client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
    # - name: Install criterion
    #   run: cargo install cargo-criterion
    # - name: Benchmark
    #   working-directory: ./rust
    #   run: cargo criterion
    # - name: Update ReadMe
    #   run:
    # - name: switching from HTTPS to SSH
    #   run: git remote set-url origin ${{ secrets.ssh }}
    # - name: check for changes
    #   run: git status
    # - name: stage changed files
    #   run: git add .
    # - name: commit changed files
    #   run: git commit -m "Auto update"
    # - name: fetch from master
    #   run: git fetch origin master
    # - name: push code to master
    #   run: git push origin HEAD:master

